[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fakexy"
version = "0.0.1"
description = "A simple scraper for fakexy.com"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GPLv3"}
keywords = ["fake-data", "scraper", "api", "fakexy"]
authors = [
  {name = "Dominik Stanisław Suchora", email = "hexderm@gmail.com" }
]

dependencies = ['requests','reliq','treerequests']

classifiers = [
  "Development Status :: 5 - Production/Stable",

  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",

  "Operating System :: OS Independent",

  "Framework :: Pytest",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
"Homepage" = "https://github.com/TUVIMEN/fakexy"

[project.optional-dependencies]
test = [
    "pytest",
    "biggusdictus",
]
pdf = [
    "img2pdf"
]

[tool.setuptools]
packages = ["fakexy"]

[project.scripts]
fakexy = "fakexy.__init__:main"
